# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - GoalsAndTasksApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build web API
        run: dotnet publish GoalsAndTasks.WebApi/GoalsAndTasks.WebApi.csproj -c Azure -o ${{env.DOTNET_ROOT}}/artifacts

      - name: Create database migration bundle
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle --project GoalsAndTasks.WebApi.DatabaseDesign/GoalsAndTasks.WebApi.DatabaseDesign.csproj -o ${{env.DOTNET_ROOT}}/artifacts/database_migration_bundle

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{env.DOTNET_ROOT}}/artifacts

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Set execute permissions for database migration bundle
        run: chmod +x ./database_migration_bundle

      - name: Run database migrations
        run: ./database_migration_bundle --connection "${{ secrets.DATABASE_CONNECTION_STRING }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GoalsAndTasksApi'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
